const nodemailer = require('nodemailer');

class EmailService {
  constructor() {
    this.transporter = null;
    this.initTransporter();
  }

  initTransporter() {
    try {
      if (!process.env.EMAIL_USER || !process.env.EMAIL_PASS) {
        console.log(' Gmail credentials not configured - Email service disabled');
        return;
      }

      this.transporter = nodemailer.createTransport({
        service: 'gmail',
        auth: {
          user: process.env.EMAIL_USER,
          pass: process.env.EMAIL_PASS
        },
        tls: {
          rejectUnauthorized: false
        },
        timeout: 10000,
        connectionTimeout: 10000
      });

      // Skip connection test to avoid timeout issues
      console.log('📧 Email service initialized (connection will be tested on first send)');
        
    } catch (error) {
      console.log(' Email service initialization failed:', error.message);
      this.transporter = null;
    }
  }

  async sendOfferEmail(candidate, letterPath) {
    if (!this.transporter) {
      console.log('Email service not configured - skipping offer email');
      return false;
    }
    try {
      const mailOptions = {
        from: process.env.EMAIL_USER || 'HR-GenAI <noreply@hrgenai.com>',
        to: candidate.email,
        subject: ` Congratulations! Job Offer - ${candidate.name}`,
        html: `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
    .container { max-width: 600px; margin: 0 auto; padding: 20px; }
    .header { background: linear-gradient(135deg, #10b981 0%, #059669 100%); color: white; padding: 30px; text-align: center; border-radius: 10px 10px 0 0; }
    .content { background: #f9f9f9; padding: 30px; border-radius: 0 0 10px 10px; }
    .offer-details { background: white; padding: 20px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #10b981; }
    .cta-button { display: inline-block; background: #10b981; color: white; padding: 15px 30px; text-decoration: none; border-radius: 8px; font-weight: bold; margin: 20px 0; }
    .footer { text-align: center; margin-top: 30px; color: #666; font-size: 12px; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1> Congratulations!</h1>
      <p>You've been selected for our team!</p>
    </div>
    
    <div class="content">
      <h2>Dear ${candidate.name},</h2>
      
      <p>We are thrilled to extend a job offer to you based on your outstanding performance in our AI-powered interview process!</p>
      
      <div class="offer-details">
        <h3> Your Interview Results</h3>
        <p><strong>Overall Score:</strong> ${candidate.interviewScore || 'Excellent'}/100</p>
        <p><strong>Growth Potential:</strong> ${candidate.growthPotential || 'High'}%</p>
        <p><strong>Retention Score:</strong> ${candidate.retentionScore || 'High'}%</p>
        <p><strong>Verdict:</strong> ${candidate.interviewSummary?.verdict || 'Strong Hire'}</p>
      </div>
      
      <p>Your skills, experience, and personality make you an excellent fit for our organization. We believe you will make significant contributions to our team.</p>
      
      <p><strong> Please find your detailed offer letter attached to this email.</strong></p>
      
      <div class="offer-details">
        <h3> Next Steps</h3>
        <ul>
          <li>Review the attached offer letter carefully</li>
          <li>Confirm your acceptance within 7 days</li>
          <li>Complete background verification process</li>
          <li>Prepare for an exciting journey with us!</li>
        </ul>
      </div>
      
      <p>We look forward to welcoming you to our team and are excited about the impact you'll make!</p>
      
      <p>Best regards,<br><strong>HR Team<br>HR-GenAI</strong></p>
    </div>
    
    <div class="footer">
      <p>© 2025 HR-GenAI. All Rights Reserved.</p>
      <p>This offer is generated by our AI-powered hiring platform.</p>
    </div>
  </div>
</body>
</html>
        `,
        attachments: [{
          filename: `Offer_Letter_${candidate.name.replace(/\s+/g, '_')}.pdf`,
          path: letterPath
        }]
      };

      await this.transporter.sendMail(mailOptions);
      console.log(` Offer letter sent to ${candidate.email}`);
      return true;
    } catch (error) {
      console.error('Offer email error:', error);
      return false;
    }
  }

  async sendRejectionEmail(candidate, letterPath) {
    if (!this.transporter) {
      console.log('Email service not configured - skipping rejection email');
      return false;
    }
    try {
      const mailOptions = {
        from: process.env.EMAIL_USER || 'HR-GenAI <noreply@hrgenai.com>',
        to: candidate.email,
        subject: `Thank you for your interest - ${candidate.name}`,
        html: `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
    .container { max-width: 600px; margin: 0 auto; padding: 20px; }
    .header { background: linear-gradient(135deg, #6366f1 0%, #4f46e5 100%); color: white; padding: 30px; text-align: center; border-radius: 10px 10px 0 0; }
    .content { background: #f9f9f9; padding: 30px; border-radius: 0 0 10px 10px; }
    .results-details { background: white; padding: 20px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #6366f1; }
    .footer { text-align: center; margin-top: 30px; color: #666; font-size: 12px; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>Thank You</h1>
      <p>For your time and interest in our organization</p>
    </div>
    
    <div class="content">
      <h2>Dear ${candidate.name},</h2>
      
      <p>Thank you for participating in our AI-powered interview process. We appreciate the time and effort you invested.</p>
      
      <div class="results-details">
        <h3> Your Interview Results</h3>
        <p><strong>Overall Score:</strong> ${candidate.interviewScore || 'N/A'}/100</p>
        <p><strong>Growth Potential:</strong> ${candidate.growthPotential || 'N/A'}%</p>
        <p><strong>Areas of Strength:</strong> ${candidate.interviewSummary?.strengths?.slice(0, 2).join(', ') || 'Multiple areas assessed'}</p>
      </div>
      
      <p>After careful consideration, we have decided to move forward with other candidates whose qualifications more closely match our current requirements.</p>
      
      <p><strong> Please find your detailed feedback letter attached to this email.</strong></p>
      
      <p>We encourage you to continue developing your skills and consider applying for future opportunities that may be a better fit.</p>
      
      <p>We wish you the best of luck in your career endeavors.</p>
      
      <p>Best regards,<br><strong>HR Team<br>HR-GenAI</strong></p>
    </div>
    
    
    <div class="footer">
      <p>© 2025 HR-GenAI. All Rights Reserved.</p>
      <p>This feedback is generated by our AI-powered hiring platform.</p>
    </div>
  </div>
</body>
</html>
        `,
        attachments: [{
          filename: `Interview_Feedback_${candidate.name.replace(/\s+/g, '_')}.pdf`,
          path: letterPath
        }]
      };

      await this.transporter.sendMail(mailOptions);
      console.log(` Rejection letter sent to ${candidate.email}`);
      return true;
    } catch (error) {
      console.error('Rejection email error:', error);
      return false;
    }
  }

  async sendInterviewInvitation({ candidateName, candidateEmail, templateName, templateDuration, templateDifficulty, interviewLink, customMessage }) {
    if (!this.transporter) {
      console.log('Email service not configured - skipping invitation email');
      return false;
    }
    try {
      const mailOptions = {
        from: process.env.EMAIL_USER || 'HR-GenAI <noreply@hrgenai.com>',
        to: candidateEmail,
        subject: `Interview Invitation - ${templateName} Position`,
        html: `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: #f5f7fa; padding: 20px; }
    .email-container { max-width: 650px; margin: 0 auto; background: white; border-radius: 16px; overflow: hidden; box-shadow: 0 4px 20px rgba(0,0,0,0.1); }
    .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 40px 30px; text-align: center; }
    .header h1 { color: white; font-size: 28px; margin-bottom: 8px; font-weight: 700; }
    .header p { color: rgba(255,255,255,0.9); font-size: 16px; }
    .content { padding: 40px 30px; }
    .greeting { font-size: 20px; color: #1a202c; margin-bottom: 20px; font-weight: 600; }
    .intro { color: #4a5568; line-height: 1.8; margin-bottom: 30px; font-size: 15px; }
    .info-box { background: linear-gradient(135deg, #f7fafc 0%, #edf2f7 100%); border-left: 4px solid #667eea; padding: 25px; border-radius: 8px; margin: 25px 0; }
    .info-box h3 { color: #2d3748; font-size: 18px; margin-bottom: 15px; font-weight: 600; }
    .info-row { display: flex; justify-content: space-between; padding: 10px 0; border-bottom: 1px solid #e2e8f0; }
    .info-row:last-child { border-bottom: none; }
    .info-label { color: #718096; font-weight: 500; }
    .info-value { color: #2d3748; font-weight: 600; }
    .cta-button { display: inline-block; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 16px 40px; text-decoration: none; border-radius: 8px; font-weight: 600; margin: 30px 0; font-size: 16px; box-shadow: 0 4px 15px rgba(102, 126, 234, 0.4); transition: transform 0.2s; }
    .cta-button:hover { transform: translateY(-2px); }
    .features { margin: 30px 0; }
    .feature-item { display: flex; align-items: start; margin: 15px 0; }
    .feature-icon { width: 24px; height: 24px; background: #667eea; border-radius: 50%; display: flex; align-items: center; justify-content: center; color: white; font-weight: bold; margin-right: 12px; flex-shrink: 0; }
    .feature-text { color: #4a5568; line-height: 1.6; }
    .instructions { background: #fffbeb; border-left: 4px solid #f59e0b; padding: 20px; border-radius: 8px; margin: 25px 0; }
    .instructions h3 { color: #92400e; margin-bottom: 15px; font-size: 16px; font-weight: 600; }
    .instructions ul { list-style: none; }
    .instructions li { color: #78350f; margin: 8px 0; padding-left: 20px; position: relative; }
    .instructions li:before { content: '✓'; position: absolute; left: 0; color: #f59e0b; font-weight: bold; }
    .custom-message { background: #e6fffa; border-left: 4px solid #38b2ac; padding: 20px; border-radius: 8px; margin: 25px 0; color: #234e52; line-height: 1.8; }
    .footer { background: #f7fafc; padding: 30px; text-align: center; border-top: 1px solid #e2e8f0; }
    .footer p { color: #718096; font-size: 13px; margin: 5px 0; }
    .footer a { color: #667eea; text-decoration: none; }
  </style>
</head>
<body>
  <div class="email-container">
    <div class="header">
      <h1>HR-GenAI</h1>
      <p>AI-Powered Hiring Intelligence Platform</p>
    </div>
    
    <div class="content">
      <div class="greeting">Dear ${candidateName},</div>
      
      <p class="intro">
        We are pleased to invite you to participate in our AI-powered interview process for the <strong>${templateName}</strong> position. 
        This is an exciting opportunity to showcase your skills through our innovative interview platform.
      </p>
      
      ${customMessage ? `<div class="custom-message"><strong>Message from HR:</strong><br>${customMessage}</div>` : ''}
      
      <div class="info-box">
        <h3>Interview Details</h3>
        <div class="info-row">
          <span class="info-label">Position</span>
          <span class="info-value">${templateName}</span>
        </div>
        <div class="info-row">
          <span class="info-label">Duration</span>
          <span class="info-value">${templateDuration} minutes</span>
        </div>
        <div class="info-row">
          <span class="info-label">Difficulty Level</span>
          <span class="info-value">${templateDifficulty}</span>
        </div>
        <div class="info-row">
          <span class="info-label">Interview Type</span>
          <span class="info-value">AI-Powered Voice Interview</span>
        </div>
      </div>
      
      <div style="text-align: center;">
        <a href="${interviewLink}" class="cta-button">Start Interview</a>
      </div>
      
      <div class="features">
        <h3 style="color: #2d3748; margin-bottom: 20px; font-size: 18px;">What to Expect</h3>
        <div class="feature-item">
          <div class="feature-icon">1</div>
          <div class="feature-text"><strong>AI Interviewer (Huma):</strong> Our intelligent AI will conduct a natural conversation with you</div>
        </div>
        <div class="feature-item">
          <div class="feature-icon">2</div>
          <div class="feature-text"><strong>Real-time Proctoring:</strong> Camera and screen monitoring for interview integrity</div>
        </div>
        <div class="feature-item">
          <div class="feature-icon">3</div>
          <div class="feature-text"><strong>Comprehensive Assessment:</strong> Technical skills, personality, and emotional intelligence evaluation</div>
        </div>
        <div class="feature-item">
          <div class="feature-icon">4</div>
          <div class="feature-text"><strong>Instant Feedback:</strong> Receive detailed results and performance analysis</div>
        </div>
      </div>
      
      <div class="instructions">
        <h3>Before You Begin</h3>
        <ul>
          <li>Ensure you have a stable internet connection</li>
          <li>Use Google Chrome or Firefox browser for best experience</li>
          <li>Enable camera and microphone permissions</li>
          <li>Find a quiet, well-lit environment</li>
          <li>Keep your government ID ready for verification</li>
          <li>Do not switch tabs or windows during the interview</li>
        </ul>
      </div>
      
      <p class="intro">
        If you have any questions or need assistance, please don't hesitate to contact our HR team.
      </p>
      
      <p style="color: #2d3748; margin-top: 30px;">
        Best regards,<br>
        <strong>HR Team</strong><br>
        HR-GenAI Platform
      </p>
    </div>
    
    <div class="footer">
      <p><strong>HR-GenAI</strong> - AI-Powered Hiring Intelligence Platform</p>
      <p>© 2025 HR-GenAI. All rights reserved.</p>
      <p style="margin-top: 15px; font-size: 12px;">This is an automated email. Please do not reply directly to this message.</p>
    </div>
  </div>
</body>
</html>
        `
      };

      if (this.transporter) {
        await this.transporter.sendMail(mailOptions);
        console.log(`Interview invitation sent to ${candidateEmail}`);
      }
      return true;
    } catch (error) {
      console.error('Interview invitation email error:', error);
      return false;
    }
  }

  async sendInterviewCompletionEmail(candidate, summary) {
    if (!this.transporter) {
      console.log('Email service not configured - skipping email');
      return false;
    }
    try {
      // Check if candidate passed and send offer letter
      const overallScore = candidate.skillDNA?.overallScore || 0;
      const passingScore = candidate.assignedTemplate?.passingScore || 70;
      const passed = overallScore >= passingScore;

      const mailOptions = {
        from: process.env.EMAIL_USER || 'HR-GenAI <noreply@hrgenai.com>',
        to: candidate.email,
        subject: passed ? ` Congratulations! Interview Passed - ${candidate.name}` : `Interview Completed - ${candidate.name}`,
        html: `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
    .container { max-width: 600px; margin: 0 auto; padding: 20px; }
    .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; text-align: center; border-radius: 10px 10px 0 0; }
    .content { background: #f9f9f9; padding: 30px; border-radius: 0 0 10px 10px; }
    .verdict { padding: 15px; margin: 20px 0; border-radius: 8px; font-weight: bold; text-align: center; font-size: 18px; }
    .verdict.strong-hire { background: #10b981; color: white; }
    .verdict.hire { background: #3b82f6; color: white; }
    .verdict.maybe { background: #f59e0b; color: white; }
    .verdict.reject { background: #ef4444; color: white; }
    .section { margin: 20px 0; }
    .section h3 { color: #667eea; margin-bottom: 10px; }
    .list { background: white; padding: 15px; border-radius: 8px; margin: 10px 0; }
    .list li { margin: 8px 0; }
    .footer { text-align: center; margin-top: 30px; color: #666; font-size: 12px; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1> HR-GenAI</h1>
      <p>AI-Powered Hiring Intelligence</p>
    </div>
    
    <div class="content">
      <h2>Hello ${candidate.name}! </h2>
      
      <p>Thank you for completing your AI interview with HR-GenAI. Here's your comprehensive evaluation:</p>
      
      <div class="verdict ${summary?.verdict?.toLowerCase().replace(' ', '-') || 'maybe'}">
        ${summary?.verdict || 'Under Review'}
      </div>
      
      <div class="section">
        <h3> Interview Summary</h3>
        <p>${summary?.summary || 'Your interview has been completed and is under review.'}</p>
      </div>
      
      <div class="section">
        <h3> Your Strengths</h3>
        <div class="list">
          <ul>
            ${summary?.strengths?.map(s => `<li>${s}</li>`).join('') || '<li>Analysis in progress</li>'}
          </ul>
        </div>
      </div>
      
      <div class="section">
        <h3> Areas for Improvement</h3>
        <div class="list">
          <ul>
            ${summary?.weaknesses?.map(w => `<li>${w}</li>`).join('') || '<li>Analysis in progress</li>'}
          </ul>
        </div>
      </div>
      
      <div class="section">
        <h3> Recommended Role</h3>
        <p><strong>${summary?.recommendedRole || 'To be determined'}</strong></p>
      </div>
      
      <div class="section">
        <h3> Your Scores</h3>
        <div class="list">
          <ul>
            <li><strong>Overall Score:</strong> ${candidate.skillDNA?.overallScore || 'N/A'}/100</li>
            <li><strong>EQ Score:</strong> ${candidate.eqAnalysis?.overallEQ || 'N/A'}/10</li>
            <li><strong>Personality Type:</strong> ${candidate.personality?.mbti || 'N/A'}</li>
          </ul>
        </div>
      </div>
      
      <div class="section">
        <h3> Next Steps</h3>
        <div class="list">
          <ul>
            ${summary?.nextSteps?.map(s => `<li>${s}</li>`).join('') || '<li>Our HR team will contact you soon</li>'}
          </ul>
        </div>
      </div>
      
      <p style="margin-top: 30px;">If you have any questions, please don't hesitate to reach out to our HR team.</p>
      
      <p>Best regards,<br><strong>HR-GenAI Team</strong></p>
    </div>
    
    <div class="footer">
      <p>© 2025 HR-GenAI. All Rights Reserved.</p>
      <p>This is an automated email. Please do not reply.</p>
    </div>
  </div>
</body>
</html>
        `
      };

      if (this.transporter) {
        await this.transporter.sendMail(mailOptions);
        console.log(` Email sent to ${candidate.email}`);
        

      }
      return true;
    } catch (error) {
      console.error('Email sending error:', error);
      return false;
    }
  }

  async sendEmail(to, subject, text) {
    if (!this.transporter) {
      console.log(' Email not sent (service not configured)');
      return false;
    }
    try {
      await this.transporter.sendMail({
        from: process.env.EMAIL_USER,
        to,
        subject,
        text
      });
      console.log(` Email sent to ${to}`);
      return true;
    } catch (error) {
      console.error('Email error:', error.message);
      return false;
    }
  }

}
module.exports = new EmailService();
