const nodemailer = require('nodemailer');

class EmailService {
  constructor() {
    this.transporter = null;
    this.initTransporter();
  }

  initTransporter() {
    try {
      if (!process.env.EMAIL_USER || !process.env.EMAIL_PASS) {
        console.log('❌ Gmail credentials not configured');
        return;
      }

      this.transporter = nodemailer.createTransport({
        service: 'gmail',
        auth: {
          user: process.env.EMAIL_USER,
          pass: process.env.EMAIL_PASS
        },
        tls: {
          rejectUnauthorized: false
        }
      });

      // Test connection
      this.transporter.verify((error, success) => {
        if (error) {
          console.log('❌ Gmail SMTP connection failed:', error.message);
          this.transporter = null;
        } else {
          console.log('✅ Gmail SMTP ready for sending emails');
        }
      });
    } catch (error) {
      console.log('❌ Email service initialization failed:', error.message);
      this.transporter = null;
    }
  }

  async sendOfferEmail(candidate, letterPath) {
    if (!this.transporter) {
      console.log('Email service not configured - skipping offer email');
      return false;
    }
    try {
      const mailOptions = {
        from: process.env.EMAIL_USER || 'HR-GenAI <noreply@hrgenai.com>',
        to: candidate.email,
        subject: `🎉 Congratulations! Job Offer - ${candidate.name}`,
        html: `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
    .container { max-width: 600px; margin: 0 auto; padding: 20px; }
    .header { background: linear-gradient(135deg, #10b981 0%, #059669 100%); color: white; padding: 30px; text-align: center; border-radius: 10px 10px 0 0; }
    .content { background: #f9f9f9; padding: 30px; border-radius: 0 0 10px 10px; }
    .offer-details { background: white; padding: 20px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #10b981; }
    .cta-button { display: inline-block; background: #10b981; color: white; padding: 15px 30px; text-decoration: none; border-radius: 8px; font-weight: bold; margin: 20px 0; }
    .footer { text-align: center; margin-top: 30px; color: #666; font-size: 12px; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>🎉 Congratulations!</h1>
      <p>You've been selected for our team!</p>
    </div>
    
    <div class="content">
      <h2>Dear ${candidate.name},</h2>
      
      <p>We are thrilled to extend a job offer to you based on your outstanding performance in our AI-powered interview process!</p>
      
      <div class="offer-details">
        <h3>🏆 Your Interview Results</h3>
        <p><strong>Overall Score:</strong> ${candidate.interviewScore || 'Excellent'}/100</p>
        <p><strong>Growth Potential:</strong> ${candidate.growthPotential || 'High'}%</p>
        <p><strong>Retention Score:</strong> ${candidate.retentionScore || 'High'}%</p>
        <p><strong>Verdict:</strong> ${candidate.interviewSummary?.verdict || 'Strong Hire'}</p>
      </div>
      
      <p>Your skills, experience, and personality make you an excellent fit for our organization. We believe you will make significant contributions to our team.</p>
      
      <p><strong>📎 Please find your detailed offer letter attached to this email.</strong></p>
      
      <div class="offer-details">
        <h3>📋 Next Steps</h3>
        <ul>
          <li>Review the attached offer letter carefully</li>
          <li>Confirm your acceptance within 7 days</li>
          <li>Complete background verification process</li>
          <li>Prepare for an exciting journey with us!</li>
        </ul>
      </div>
      
      <p>We look forward to welcoming you to our team and are excited about the impact you'll make!</p>
      
      <p>Best regards,<br><strong>HR Team<br>HR-GenAI</strong></p>
    </div>
    
    <div class="footer">
      <p>© 2025 HR-GenAI. All Rights Reserved.</p>
      <p>This offer is generated by our AI-powered hiring platform.</p>
    </div>
  </div>
</body>
</html>
        `,
        attachments: [{
          filename: `Offer_Letter_${candidate.name.replace(/\s+/g, '_')}.pdf`,
          path: letterPath
        }]
      };

      await this.transporter.sendMail(mailOptions);
      console.log(`✅ Offer letter sent to ${candidate.email}`);
      return true;
    } catch (error) {
      console.error('Offer email error:', error);
      return false;
    }
  }

  async sendRejectionEmail(candidate, letterPath) {
    if (!this.transporter) {
      console.log('Email service not configured - skipping rejection email');
      return false;
    }
    try {
      const mailOptions = {
        from: process.env.EMAIL_USER || 'HR-GenAI <noreply@hrgenai.com>',
        to: candidate.email,
        subject: `Thank you for your interest - ${candidate.name}`,
        html: `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
    .container { max-width: 600px; margin: 0 auto; padding: 20px; }
    .header { background: linear-gradient(135deg, #6366f1 0%, #4f46e5 100%); color: white; padding: 30px; text-align: center; border-radius: 10px 10px 0 0; }
    .content { background: #f9f9f9; padding: 30px; border-radius: 0 0 10px 10px; }
    .results-details { background: white; padding: 20px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #6366f1; }
    .footer { text-align: center; margin-top: 30px; color: #666; font-size: 12px; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>Thank You</h1>
      <p>For your time and interest in our organization</p>
    </div>
    
    <div class="content">
      <h2>Dear ${candidate.name},</h2>
      
      <p>Thank you for participating in our AI-powered interview process. We appreciate the time and effort you invested.</p>
      
      <div class="results-details">
        <h3>📊 Your Interview Results</h3>
        <p><strong>Overall Score:</strong> ${candidate.interviewScore || 'N/A'}/100</p>
        <p><strong>Growth Potential:</strong> ${candidate.growthPotential || 'N/A'}%</p>
        <p><strong>Areas of Strength:</strong> ${candidate.interviewSummary?.strengths?.slice(0, 2).join(', ') || 'Multiple areas assessed'}</p>
      </div>
      
      <p>After careful consideration, we have decided to move forward with other candidates whose qualifications more closely match our current requirements.</p>
      
      <p><strong>📎 Please find your detailed feedback letter attached to this email.</strong></p>
      
      <p>We encourage you to continue developing your skills and consider applying for future opportunities that may be a better fit.</p>
      
      <p>We wish you the best of luck in your career endeavors.</p>
      
      <p>Best regards,<br><strong>HR Team<br>HR-GenAI</strong></p>
    </div>
    
    
    <div class="footer">
      <p>© 2025 HR-GenAI. All Rights Reserved.</p>
      <p>This feedback is generated by our AI-powered hiring platform.</p>
    </div>
  </div>
</body>
</html>
        `,
        attachments: [{
          filename: `Interview_Feedback_${candidate.name.replace(/\s+/g, '_')}.pdf`,
          path: letterPath
        }]
      };

      await this.transporter.sendMail(mailOptions);
      console.log(`✅ Rejection letter sent to ${candidate.email}`);
      return true;
    } catch (error) {
      console.error('Rejection email error:', error);
      return false;
    }
  }

  async sendInterviewInvitation({ candidateName, candidateEmail, interviewDate, interviewTime, interviewLink, hrEmail }) {
    if (!this.transporter) {
      console.log('Email service not configured - skipping invitation email');
      return false;
    }
    try {
      const mailOptions = {
        from: process.env.EMAIL_USER || 'HR-GenAI <noreply@hrgenai.com>',
        to: candidateEmail,
        cc: hrEmail,
        subject: `🎯 Interview Invitation - ${candidateName}`,
        html: `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
    .container { max-width: 600px; margin: 0 auto; padding: 20px; }
    .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; text-align: center; border-radius: 10px 10px 0 0; }
    .content { background: #f9f9f9; padding: 30px; border-radius: 0 0 10px 10px; }
    .interview-details { background: white; padding: 20px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #667eea; }
    .cta-button { display: inline-block; background: #667eea; color: white; padding: 15px 30px; text-decoration: none; border-radius: 8px; font-weight: bold; margin: 20px 0; }
    .footer { text-align: center; margin-top: 30px; color: #666; font-size: 12px; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>🧬 HR-GenAI</h1>
      <p>AI-Powered Interview Invitation</p>
    </div>
    
    <div class="content">
      <h2>Hello ${candidateName}! 👋</h2>
      
      <p>Congratulations! You have been selected for an AI-powered interview with our HR-GenAI platform.</p>
      
      <div class="interview-details">
        <h3>📅 Interview Details</h3>
        <p><strong>Date:</strong> ${interviewDate}</p>
        <p><strong>Time:</strong> ${interviewTime}</p>
        <p><strong>Duration:</strong> Approximately 60 minutes</p>
        <p><strong>Type:</strong> AI Voice Interview with Huma</p>
      </div>
      
      <p>Our AI interviewer, Huma, will conduct a comprehensive assessment including:</p>
      <ul>
        <li>🎯 Role-specific technical questions</li>
        <li>🧠 Personality and EQ evaluation</li>
        <li>💬 Natural conversation assessment</li>
        <li>📊 Real-time performance analysis</li>
      </ul>
      
      <div style="text-align: center;">
        <a href="${interviewLink}" class="cta-button">🚀 Start Your Interview</a>
      </div>
      
      <div class="interview-details">
        <h3>📋 Before You Start</h3>
        <ul>
          <li>Ensure stable internet connection</li>
          <li>Use Chrome or Firefox browser</li>
          <li>Enable camera and microphone access</li>
          <li>Find a quiet, well-lit environment</li>
        </ul>
      </div>
      
      <p>If you have any questions or need to reschedule, please contact our HR team immediately.</p>
      
      <p>Best of luck with your interview!</p>
      
      <p>Best regards,<br><strong>HR-GenAI Team</strong></p>
    </div>
    
    <div class="footer">
      <p>© 2025 HR-GenAI. All Rights Reserved.</p>
      <p>Interview Link: <a href="${interviewLink}">${interviewLink}</a></p>
    </div>
  </div>
</body>
</html>
        `
      };

      if (this.transporter) {
        await this.transporter.sendMail(mailOptions);
        console.log(`✅ Interview invitation sent to ${candidateEmail}`);
      }
      return true;
    } catch (error) {
      console.error('Interview invitation email error:', error);
      return false;
    }
  }

  async sendInterviewCompletionEmail(candidate, summary) {
    if (!this.transporter) {
      console.log('Email service not configured - skipping email');
      return false;
    }
    try {
      // Check if candidate passed and send offer letter
      const overallScore = candidate.skillDNA?.overallScore || 0;
      const passingScore = candidate.assignedTemplate?.passingScore || 70;
      const passed = overallScore >= passingScore;

      const mailOptions = {
        from: process.env.EMAIL_USER || 'HR-GenAI <noreply@hrgenai.com>',
        to: candidate.email,
        subject: passed ? `🎉 Congratulations! Interview Passed - ${candidate.name}` : `Interview Completed - ${candidate.name}`,
        html: `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
    .container { max-width: 600px; margin: 0 auto; padding: 20px; }
    .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; text-align: center; border-radius: 10px 10px 0 0; }
    .content { background: #f9f9f9; padding: 30px; border-radius: 0 0 10px 10px; }
    .verdict { padding: 15px; margin: 20px 0; border-radius: 8px; font-weight: bold; text-align: center; font-size: 18px; }
    .verdict.strong-hire { background: #10b981; color: white; }
    .verdict.hire { background: #3b82f6; color: white; }
    .verdict.maybe { background: #f59e0b; color: white; }
    .verdict.reject { background: #ef4444; color: white; }
    .section { margin: 20px 0; }
    .section h3 { color: #667eea; margin-bottom: 10px; }
    .list { background: white; padding: 15px; border-radius: 8px; margin: 10px 0; }
    .list li { margin: 8px 0; }
    .footer { text-align: center; margin-top: 30px; color: #666; font-size: 12px; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>🧬 HR-GenAI</h1>
      <p>AI-Powered Hiring Intelligence</p>
    </div>
    
    <div class="content">
      <h2>Hello ${candidate.name}! 👋</h2>
      
      <p>Thank you for completing your AI interview with HR-GenAI. Here's your comprehensive evaluation:</p>
      
      <div class="verdict ${summary?.verdict?.toLowerCase().replace(' ', '-') || 'maybe'}">
        ${summary?.verdict || 'Under Review'}
      </div>
      
      <div class="section">
        <h3>📋 Interview Summary</h3>
        <p>${summary?.summary || 'Your interview has been completed and is under review.'}</p>
      </div>
      
      <div class="section">
        <h3>✅ Your Strengths</h3>
        <div class="list">
          <ul>
            ${summary?.strengths?.map(s => `<li>${s}</li>`).join('') || '<li>Analysis in progress</li>'}
          </ul>
        </div>
      </div>
      
      <div class="section">
        <h3>📈 Areas for Improvement</h3>
        <div class="list">
          <ul>
            ${summary?.weaknesses?.map(w => `<li>${w}</li>`).join('') || '<li>Analysis in progress</li>'}
          </ul>
        </div>
      </div>
      
      <div class="section">
        <h3>🎯 Recommended Role</h3>
        <p><strong>${summary?.recommendedRole || 'To be determined'}</strong></p>
      </div>
      
      <div class="section">
        <h3>📊 Your Scores</h3>
        <div class="list">
          <ul>
            <li><strong>Overall Score:</strong> ${candidate.skillDNA?.overallScore || 'N/A'}/100</li>
            <li><strong>EQ Score:</strong> ${candidate.eqAnalysis?.overallEQ || 'N/A'}/10</li>
            <li><strong>Personality Type:</strong> ${candidate.personality?.mbti || 'N/A'}</li>
          </ul>
        </div>
      </div>
      
      <div class="section">
        <h3>🔮 Next Steps</h3>
        <div class="list">
          <ul>
            ${summary?.nextSteps?.map(s => `<li>${s}</li>`).join('') || '<li>Our HR team will contact you soon</li>'}
          </ul>
        </div>
      </div>
      
      <p style="margin-top: 30px;">If you have any questions, please don't hesitate to reach out to our HR team.</p>
      
      <p>Best regards,<br><strong>HR-GenAI Team</strong></p>
    </div>
    
    <div class="footer">
      <p>© 2025 HR-GenAI. All Rights Reserved.</p>
      <p>This is an automated email. Please do not reply.</p>
    </div>
  </div>
</body>
</html>
        `
      };

      if (this.transporter) {
        await this.transporter.sendMail(mailOptions);
        console.log(`✅ Email sent to ${candidate.email}`);
        

      }
      return true;
    } catch (error) {
      console.error('Email sending error:', error);
      return false;
    }
  }

  async sendEmail(to, subject, text) {
    if (!this.transporter) {
      console.log('⚠️ Email not sent (service not configured)');
      return false;
    }
    try {
      await this.transporter.sendMail({
        from: process.env.EMAIL_USER,
        to,
        subject,
        text
      });
      console.log(`✅ Email sent to ${to}`);
      return true;
    } catch (error) {
      console.error('Email error:', error.message);
      return false;
    }
  }

}
module.exports = new EmailService();
