const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

class LetterGenerationService {
    constructor() {
        this.companyName = 'HR-GenAI';
        this.companyAddress = 'AI-Powered Hiring Intelligence Platform';
    }

    // Generate offer letter PDF
    async generateOfferLetter(candidate, jobDetails = {}) {
        return new Promise((resolve, reject) => {
            try {
                const doc = new PDFDocument({ margin: 50 });
                const fileName = `offer_letter_${candidate.name.replace(/\s+/g, '_')}_${Date.now()}.pdf`;
                const filePath = path.join(__dirname, '../../uploads/letters', fileName);

                // Ensure directory exists
                const dir = path.dirname(filePath);
                if (!fs.existsSync(dir)) {
                    fs.mkdirSync(dir, { recursive: true });
                }

                const stream = fs.createWriteStream(filePath);
                doc.pipe(stream);

                // Header
                doc.fontSize(20).fillColor('#2563eb').text(this.companyName, { align: 'center' });
                doc.fontSize(12).fillColor('#666').text(this.companyAddress, { align: 'center' });
                doc.moveDown(2);

                // Date
                doc.fontSize(12).fillColor('#000').text(`Date: ${new Date().toLocaleDateString()}`, { align: 'right' });
                doc.moveDown();

                // Candidate details
                doc.text(`${candidate.name}`);
                doc.text(`${candidate.email}`);
                if (candidate.phone) doc.text(`${candidate.phone}`);
                if (candidate.location) doc.text(`${candidate.location}`);
                doc.moveDown();

                // Subject
                doc.fontSize(14).fillColor('#2563eb').text('Subject: Job Offer - Congratulations!', { underline: true });
                doc.moveDown();

                // Body
                doc.fontSize(12).fillColor('#000');
                doc.text(`Dear ${candidate.name},`);
                doc.moveDown();

                doc.text('Congratulations! We are pleased to offer you a position with our organization based on your exceptional performance in our AI-powered interview process.');
                doc.moveDown();

                // Interview results
                doc.text('Your Interview Results:', { underline: true });
                doc.text(`• Overall Score: ${candidate.interviewScore || 'N/A'}/100`);
                doc.text(`• Growth Potential: ${candidate.growthPotential || 'N/A'}%`);
                doc.text(`• Retention Score: ${candidate.retentionScore || 'N/A'}%`);
                doc.text(`• Verdict: ${candidate.interviewSummary?.verdict || 'Strong Candidate'}`);
                doc.moveDown();

                // Job details
                doc.text('Position Details:', { underline: true });
                doc.text(`• Position: ${jobDetails.position || candidate.appliedFor || 'Software Developer'}`);
                doc.text(`• Department: ${jobDetails.department || 'Technology'}`);
                doc.text(`• Start Date: ${jobDetails.startDate || 'To be discussed'}`);
                doc.text(`• Salary: ${jobDetails.salary || 'As per industry standards'}`);
                doc.moveDown();

                // Key strengths
                if (candidate.interviewSummary?.strengths?.length > 0) {
                    doc.text('Your Key Strengths:', { underline: true });
                    candidate.interviewSummary.strengths.slice(0, 3).forEach(strength => {
                        doc.text(`• ${strength}`);
                    });
                    doc.moveDown();
                }

                // Next steps
                doc.text('Next Steps:', { underline: true });
                doc.text('• Please confirm your acceptance within 7 days');
                doc.text('• HR will contact you for onboarding details');
                doc.text('• Complete background verification process');
                doc.text('• Prepare for your exciting journey with us!');
                doc.moveDown();

                doc.text('We look forward to welcoming you to our team and are excited about the contributions you will make.');
                doc.moveDown();

                doc.text('Best regards,');
                doc.text('HR Team');
                doc.text(this.companyName);

                // Footer
                doc.fontSize(10).fillColor('#666');
                doc.text('This is an automated offer letter generated by HR-GenAI platform.', 50, doc.page.height - 50);

                doc.end();

                stream.on('finish', () => {
                    resolve({ filePath, fileName });
                });

                stream.on('error', reject);

            } catch (error) {
                reject(error);
            }
        });
    }

    // Generate rejection letter PDF
    async generateRejectionLetter(candidate) {
        return new Promise((resolve, reject) => {
            try {
                const doc = new PDFDocument({ margin: 50 });
                const fileName = `rejection_letter_${candidate.name.replace(/\s+/g, '_')}_${Date.now()}.pdf`;
                const filePath = path.join(__dirname, '../../uploads/letters', fileName);

                // Ensure directory exists
                const dir = path.dirname(filePath);
                if (!fs.existsSync(dir)) {
                    fs.mkdirSync(dir, { recursive: true });
                }

                const stream = fs.createWriteStream(filePath);
                doc.pipe(stream);

                // Header
                doc.fontSize(20).fillColor('#2563eb').text(this.companyName, { align: 'center' });
                doc.fontSize(12).fillColor('#666').text(this.companyAddress, { align: 'center' });
                doc.moveDown(2);

                // Date
                doc.fontSize(12).fillColor('#000').text(`Date: ${new Date().toLocaleDateString()}`, { align: 'right' });
                doc.moveDown();

                // Candidate details
                doc.text(`${candidate.name}`);
                doc.text(`${candidate.email}`);
                if (candidate.phone) doc.text(`${candidate.phone}`);
                if (candidate.location) doc.text(`${candidate.location}`);
                doc.moveDown();

                // Subject
                doc.fontSize(14).fillColor('#dc2626').text('Subject: Interview Results - Thank You', { underline: true });
                doc.moveDown();

                // Body
                doc.fontSize(12).fillColor('#000');
                doc.text(`Dear ${candidate.name},`);
                doc.moveDown();

                doc.text('Thank you for your interest in our organization and for taking the time to participate in our AI-powered interview process.');
                doc.moveDown();

                // Interview results
                doc.text('Your Interview Results:', { underline: true });
                doc.text(`• Overall Score: ${candidate.interviewScore || 'N/A'}/100`);
                doc.text(`• Growth Potential: ${candidate.growthPotential || 'N/A'}%`);
                doc.text(`• Areas of Strength: ${candidate.interviewSummary?.strengths?.slice(0, 2).join(', ') || 'Multiple areas assessed'}`);
                doc.moveDown();

                doc.text('After careful consideration of your interview performance, we have decided to move forward with other candidates whose qualifications more closely match our current requirements.');
                doc.moveDown();

                // Feedback
                if (candidate.interviewSummary?.weaknesses?.length > 0) {
                    doc.text('Areas for Future Development:', { underline: true });
                    candidate.interviewSummary.weaknesses.slice(0, 3).forEach(weakness => {
                        doc.text(`• ${weakness}`);
                    });
                    doc.moveDown();
                }

                doc.text('We encourage you to continue developing your skills and consider applying for future opportunities that may be a better fit.');
                doc.moveDown();

                doc.text('We appreciate your time and effort, and we wish you the best of luck in your career endeavors.');
                doc.moveDown();

                doc.text('Best regards,');
                doc.text('HR Team');
                doc.text(this.companyName);

                // Footer
                doc.fontSize(10).fillColor('#666');
                doc.text('This is an automated letter generated by HR-GenAI platform.', 50, doc.page.height - 50);

                doc.end();

                stream.on('finish', () => {
                    resolve({ filePath, fileName });
                });

                stream.on('error', reject);

            } catch (error) {
                reject(error);
            }
        });
    }
}

module.exports = LetterGenerationService;